sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.5"

before_install:
  - pip3 install cwltool
  - docker build -t danipt .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /danipt/.travis/unit-test.sh danipt
  # Unit tests
  - docker run --entrypoint /danipt/functional_tests/danipt-test.sh danipt -p danipt -d /danipt/functional_tests/test_data -v

  # CWL definition test
  - cwltool danipt.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
